name: Build and Deploy to Build Branch

on:
  workflow_dispatch:  # Allows manual or programmatic trigger
  push:
    branches:
      - main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensures a full repository checkout

    - name: Show current directory and Git status
      run: |
        pwd
        ls -la
        git status


    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
      
    # Install dependencies and build
    - name: Install and Build
      working-directory: frontend
      run: |
        npm install
        npm run build

    # Push build folder to build branch
    - name: Deploy build folder to build branch
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git checkout --orphan build
        git rm -rf .
        cp -R frontend/dist/. .
        git --work-tree=frontend/dist add --all
        git --work-tree=frontend/dist commit -m "Deploy build"
        git push --force origin build
