name: Build and Deploy to Build Branch

on:
  workflow_dispatch:  # Allows manual or programmatic trigger
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensures a full repository checkout

    - name: Show current directory and Git status
      run: |
        pwd
        ls -la
        git status


    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
      
    # Install dependencies and build
    - name: Install and Build
      working-directory: frontend
      run: |
        npm install
        npm run build

    # Push build folder to build branch
    - name: Deploy build folder to build branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout --orphan build
        git --work-tree=frontend/build add --all
        git --work-tree=frontend/build commit -m "Deploy build"
        git push --force origin build
